apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-k3s-deployment
  annotations:
    commitID: "cc1762f66faa2c30e3afff4c8f2f6963bf480a29"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-k3s
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: hello-world-k3s
    spec:
      containers:
        - name: hello-world-k3s
          image: 'xavelo/hello-world-k3s:cc1762f66faa2c30e3afff4c8f2f6963bf480a29'
          ports:
            - containerPort: 80
