apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-k3s-deployment
  annotations:
    commitID: "3903a29e52d5ae7ee02eca90c26fc7b32fecbc0c"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-k3s
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: hello-world-k3s
    spec:
      containers:
        - name: hello-world-k3s
          image: 'xavelo/hello-world-k3s:3903a29e52d5ae7ee02eca90c26fc7b32fecbc0c'
          ports:
            - containerPort: 80
